version: '3'

services:
  web:
    build: ~/Sites/docker-images/php-apache
    depends_on:
      - postgres
      - redis
    ports: 
      - "8000:80"
    volumes:
      - .:/var/www/html
  node:
    build: ~/Sites/docker-images/node
    ports: 
      - "3000:3000"
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5431:5431"
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: alipes
      POSTGRES_DB: alipes
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data